### PR TITLE
Use runtime org.kde.Platform version 5.15-21.08

### PR DESCRIPTION
**Pull request by palvarez89**

### CODE REVIEW

**Comment by palvarez89** [comment]
With this, I was able to uninstall `org.freedesktop.Platform.GL.default` and `org.freedesktop.Platform.VAAPI.Intel` from branch 20.08 and get quassel working

**Review by travier — APPROVED** [review]

**Comment by travier** [comment]
Works for me

**Comment by travier** [comment]
For some reason the @flathub/kde team does not have merge powers here. @barthalion

**Comment by tsdgeos** [comment]
Quassel is not a KDE app, i don't see a particular reason we should merge powers here.

**Comment by travier** [comment]
> Quassel is not a KDE app, i don't see a particular reason we should merge powers here.

Oh, my bad then.

**Comment by travier** [comment]
Ping @TingPing maybe?

**Comment by travier** [comment]
Thanks!

**Pull request merged**
