### PR TITLE
Add permission for org.freedesktop.UDisks2

### PR DESCRIPTION
**Pull request by dgcampea**

### CODE REVIEW

**Comment by TingPing** [comment]
This is a scary permission that no IRC client should have...

**Comment by dgcampea** [comment]
Running this via terminal will show it warning about not being able to access UDisks2, if I am not mistaken, when one needs to use the file manager to open a file (such as SSL certs for SASL EXTERNAL).

**Comment by TingPing** [comment]
You don't use UDisks for file system access, you use it to format, partition, or simply list drives on the host. I imagine this is for some sysinfo plugin maybe?

**Comment by dgcampea** [comment]
The warning shows up as soon I click Load on 'Use SSL Key' on Setting->IRC->Identities->Advanced
```
2019-12-30 17:26:08 [Warn ] Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
```
Although it seems able to work fine without this permission. Should it be considered unnecessary then?

**Comment by TingPing** [comment]
> Although it seems able to work fine without this permission. Should it be considered unnecessary then?

I would say be conservative about permissions unless they are understood. It shouldn't be hard to track down what actually uses it but it sounds unnecessary for that specific feature.

**Comment by dgcampea** [comment]
Maybe this?
- https://github.com/quassel/quassel/blob/cc6e7c08709c4e761e2fd9c2e322751015497003/src/qtui/settingspages/identityeditwidget.cpp#L362
and some circumstantial info: https://bugs.kde.org/show_bug.cgi?id=403250#c4

Maybe disallowing this permission makes you unable to select SSL certs stored in removable drives (anything that requires UDisks2)?

If that's the case then maybe a README note with instructions should suffice since this would be considered a 'power feature'.

**Comment by TingPing** [comment]
Ok so the file chooser can show unmounted disks it sounds like?

Anyway that a different bug because it should be using the portal file chooser not its own internal one.

**Pull request closed without merging**
